### ISSUE TITLE
hello i have a problem with the clan tag

### ISSUE THREAD

**Issue by turpez** [mchurichi/clash-of-clans-stats#3]
Hello, I have a problem with the tag of the clan I place it where in the code thank you in advance

**Comment by mchurichi** [comment]
Hey @turpez, sorry but this project is in a super early stage and abandoned, right now isn't doing much other than reading the clan info from the CoC API.

**Comment by turpez** [comment]
Ok but on the web page there is only hello world ? and nothing about the clan

**Comment by mchurichi** [comment]
Right, it doesn't show any clan info right now. Hope you find another project that works for you.

**Comment by turpez** [comment]
I hope so too, thanks anyway
